### ISSUE TITLE
Can't install version 4 of the plugin

### ISSUE THREAD

**Issue by Langelus** [jellyfin/jellyfin-plugin-nextpvr#45]
Jellyfin Version: 10.8.8

Trying to install version 4.0.0 of this plugin since it's the latest version still compatible with NextPVR 4.x but get this in the logs and marked as not supported in the web gui. 

Failed to load assembly /config/data/plugins/NextPVR_4.0.0.0/NextPvr.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.

Would it be possible to either make this old version work or make a humble request to add a "legacy mode" to the newer versions of this plugin? Updating NextPVR is unfortunately a no go for me since they dropped support for Softcams in version 5 which is sad.

Thanks!

**Comment by crobibero** [comment]
No, we don't support legacy versions.
